### PR TITLE
Move contextual info out of scope section

### PR DESCRIPTION
**Pull request by dontcallmedom**
per @wseltzer suggestion

### CODE REVIEW

**Comment by anssiko** [comment]
Add `<h2>Background</h2>` (and add an entry to `<ul id="navbar">` accordingly)?

**Comment by anssiko** [comment]
Otherwise, LGTM.

**Comment by dontcallmedom** [comment]
I'm hesitant to change the typical structure of a charter... @wseltzer any opinion?

**Comment by anssiko** [comment]
See https://www.w3.org/2016/11/webplatform-charter.html#background

**Comment by dontcallmedom** [comment]
much easier if there is a precedent indeed :) updated accordingly

**Pull request merged**
